Pointage\userBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: Pointage\userBundle\Entity\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '45'
            nullable: TRUE
        prenom:
            type: string
            length: '45'
            nullable: TRUE
        fonction:
            type: string
            length: '45'
            nullable: TRUE
    lifecycleCallbacks: {  }
